mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'catalog.views.home'),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^admin/catalog/product/add/$', 'catalog.views.product_form', name="start"),
    url(r'^admin/catalog/product/(?P<id>\d+)/$', 'catalog.views.product_edit', name="start"),
    url(r'^admin/catalog/product/edit_ajax_related/$', 'catalog.views.product_edit_afax_related'),
    url(r'^admin/catalog/product/edit_ajax_research/(?P<pr_id>\d+)$', 'catalog.views.product_edit_ajax_research'),
    url(r'^admin/email/', 'shop.views.admin_email'),
    url(r'^admin/settings/', 'accounts.views.admin_settings'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'ajax-upload$', 'catalog.views.import_uploader', name="my_ajax_upload"),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^cart/', include('shop.urls')),
    url(r'^login/', 'accounts.views.ajax_login'),
    url(r'^logout/', 'accounts.views.logout'),
    url(r'^registration/$', 'accounts.views.registration'),
    url(r'^user/orders/', 'accounts.views.my_orders'),
    url(r'^user/order/(?P<id>\d+)/$', 'accounts.views.my_order'),
    url(r'', include('pages.urls')),
)

mysite/shop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'shop.views.cart'),
    url(r'^order/$', 'shop.views.order'),
    url(r'^add_in_cart/(?P<id>\d+)/$', 'shop.views.add_in_cart'),
    url(r'^del_in_cart/(?P<id>\d+)/$', 'shop.views.del_in_cart'),
    url(r'^remove_in_cart/(?P<id>\d+)/$', 'shop.views.remove_in_cart'),
    url(r'^cart_top_ajax/$', 'shop.views.cart_top_ajax')
)

mysite/accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Модифицируем поле email.
# _meta это экземпляр django.db.models.options.Options, который хранит данные о модели.
# Это немного хак, но я пока не нашел более простого способа переопределить поле из базовой модели.
AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False


class User(AbstractUser):
    # Добавляем поля аватара. null=True не нужен т.к. в БД это обычное текстовое поле.
    # max_length=1000 - по умолчанию значение 100, пару раз натыкался на глюки при длинных названиях файлов,
    # может в 1.5 уже и не нужно, но там все так же 100.
    avatar = models.ImageField(_(u'avatar'), upload_to='accounts/avatar/%Y/%m/', blank=True, max_length=1000)
    # Добавляем поле дня рождения.
    birthday = models.DateField(_(u'birthday'), blank=True, null=True)
    phone = models.CharField("Телефон", max_length=200, unique=True, blank=False)

    region = models.CharField("Область", max_length=200, blank=True)
    city = models.CharField("Город", max_length=200, blank=True)
    index = models.CharField("Индекс", max_length=200, blank=True)
    address2 = models.CharField("Адрес", max_length=200, blank=True)


class Address(models.Model):
    region = models.CharField("Область", max_length=200, blank=True)
    city = models.CharField("Город", max_length=200, blank=True)
    index = models.CharField("Индекс", max_length=200, blank=True)
    address = models.CharField("Адрес", max_length=200, blank=True)
    user = models.ForeignKey(User, verbose_name="Пользователь", blank=True, null=True)


class SiteSettings(models.Model):
    site_name = models.CharField('Название сайта', max_length=200)
    description = models.CharField('Description', max_length=200)
    keywords = models.CharField('Keywords', max_length=200)

    phone = models.CharField('Телефон', max_length=200)
    email = models.CharField('E-mail', max_length=200)

    vk = models.CharField('Вк', max_length=200)
    inst = models.CharField('Instagram', max_length=200)

    head_banner = models.ImageField("Баннер (главный)", upload_to="static/uploads/", blank=True, max_length=1000)

    def save(self, *args, **kwargs):
        if self.head_banner == '':
            model = SiteSettings.objects.get(id=self.id)
            self.head_banner = model.head_banner
        super(SiteSettings, self).save(*args, **kwargs)

mysite/accounts/forms.py
# coding: utf8
from .models import User, SiteSettings
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


# Допиливаем форму добавления пользователя. В Meta.model указываем нашу модель.
# Добавляем обязательное поле email и фиксим один метод, который почему-то явно
# стандартную модель, а не рекомендуемый get_user_model.
class AdminUserAddForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


# Допиливаем форму редактирования пользователя. В Meta.model указываем нашу модель.
class AdminUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = "__all__"


class LoginForm(forms.Form):
    login = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    is_remember = forms.BooleanField(required=False)

    # def clean(self):
    #     cleaned_data = super(LoginForm, self).clean()
    #     login = cleaned_data.get("login")
    #
    #     try:
    #         user = User.objects.get(phone=login)
    #     except User.DoesNotExist:
    #         raise forms.ValidationError("Не правельный логин или пароль")
    #
    #     return cleaned_data


class UserRegistrationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone']


class SiteSettingsForm(forms.ModelForm):

    class Meta:
        model = SiteSettings
        fields = '__all__'

mysite/accounts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.core.context_processors import csrf
from django.http import Http404
from django.contrib import auth
from shop.additions import unserialize_get, translit, random_str
from shop.models import Order
from forms import LoginForm, UserRegistrationForm, SiteSettingsForm
from models import User, SiteSettings
from catalog.models import Product


def ajax_login(request):
    args = {}
    args.update(csrf(request))
    args['form'] = LoginForm()

    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            try:
                us = User.objects.get(phone=request.POST.get('login'))
                username = us.username
                password = request.POST.get('password')
                user = auth.authenticate(username=username, password=password)
                if user is not None and user.is_active:
                    auth.login(request, user)
                    return render_to_response("yes.html", {'us': us})
            except User.DoesNotExist:
                pass
        args['form'] = form
        args['error'] = "Данные введены не верно!"
        return render_to_response("ajax_login.html", args)

    return render_to_response("ajax_login.html", args)


def logout(request):
    auth.logout(request)
    # Перенаправление на страницу.
    return HttpResponseRedirect("/")


def registration(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserRegistrationForm()
    if request.POST:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            password = random_str(6)
            us = form.save(commit=False)
            us.username = translit(us.first_name) + '_' + random_str(3)
            us.set_password(password)
            us.save()
            return render_to_response("registration_thank.html", {'username': us.phone, 'password': password})
        args['form'] = form
    return render_to_response("registration.html", args)


def my_orders(request):
    status_mass = {
        '0': 'Обрабатывется',
        '1': 'Ждёт оплаты',
        '2': 'Оплачен',
        '3': 'Отправлен',
    }
    if request.user.is_authenticated():
        orders = Order.objects.filter(user=request.user)
        for order in orders:
            mass_pr = order.products.split("==")
            mass_pr_new = []
            for prr in mass_pr:
                if prr != '':
                    new_pr = Product()
                    data = prr.split(";")
                    new_pr.image = data[0]
                    new_pr.name = data[1]
                    new_pr.price = data[2]
                    new_pr.count = data[3]
                    new_pr.price_all = data[4]
                    mass_pr_new.append(new_pr)
            order.products = mass_pr_new
            order.status = status_mass[order.status]
        orders = reversed(orders)
        return render_to_response("my_orders.html", {'orders': orders})
    return render_to_response("my_orders_not_registered.html")


def my_order(request, id=-1):
    if request.user.is_authenticated():
        try:
            order = Order.objects.get(id=id)
            if request.user == order.user:
                mass_pr = order.products.split("==")
                mass_pr_new = []
                for prr in mass_pr:
                    if prr != '':
                        new_pr = Product()
                        data = prr.split(";")
                        new_pr.image = data[0]
                        new_pr.name = data[1]
                        new_pr.price = data[2]
                        new_pr.count = data[3]
                        new_pr.price_all = data[4]
                        mass_pr_new.append(new_pr)
                order.products = mass_pr_new
                return render_to_response("my_order.html", {'order': order})
        except Order.DoesNotExist:
            pass
    raise Http404("Страница не найдена!")


def admin_settings(request):
    if request.user.is_authenticated():
        args = {}
        args.update(csrf(request))
        try:
            model = SiteSettings.objects.get(id=1)
            args['form'] = SiteSettingsForm(instance=model)
        except SiteSettings.DoesNotExist:
            args['form'] = SiteSettingsForm()

        if request.POST:
            form = SiteSettingsForm(request.POST, request.FILES)
            if form.is_valid():
                model = form.save(commit=False)
                model.id = 1
                model.save()
                return redirect('/admin/')
            else:
                args['form'] = form

        return render_to_response("admin_settings.html", args)
    else:
        return redirect('/admin/')

mysite/accounts/templates/admin_settings.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block extrahead %}{{ block.super }}
    <meta charset="UTF-8">
    <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
    <script src="{% static "ajaxuploader/js/fileuploader.js" %}" ></script>
    <link href="{% static "ajaxuploader/css/fileuploader.css" %}" media="screen" rel="stylesheet" type="text/css" />
    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />

    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/redactor/jquery.redactor.init.js"></script>
    <script type="text/javascript" src="/static/redactor/redactor.js"></script>
    <script type="text/javascript" src="/static/redactor/langs/ru.js"></script>
    <style>
    .breadcrumb {
        display: none;
    }
    #product_form input[type="text"] {
        width: 450px;
    }
    </style>
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block my_left_menu %}
<div class="left-nav" id="left-nav">
	<ul>
		<li>
			<a href="/admin/"><i class="icon-home"></i>Начало
			</a>
		</li>
		<li>
			<a href="/admin/accounts/user/"><i class="icon-chevron-right"></i>Accounts
			</a>
			<ul>
				<li>
					<a href="/admin/accounts/user/">Пользователи</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/banners/rightbanner/"><i class="icon-chevron-right"></i>Banners
			</a>
			<ul>
				<li>
					<a href="/admin/banners/rightbanner/">Баннеры справа</a>
				</li>
				<li>
					<a href="/admin/banners/slider/">Слайдер</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/catalog/category/"><i class="icon-chevron-right"></i>Catalog
			</a>
			<ul>
				<li>
					<a href="/admin/catalog/category/">Категории</a>
				</li>
				<li>
					<a href="/admin/catalog/product/">Товары</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/pages/page/"><i class="icon-chevron-right"></i>Pages
			</a>
			<ul>
				<li>
					<a href="/admin/pages/page/">Страницы</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/shop/typedelivery/"><i class="icon-chevron-right"></i>Shop
			</a>
			<ul>
				<li>
					<a href="/admin/shop/typedelivery/">Варианты доставки</a>
				</li>
				<li>
					<a href="/admin/shop/order/">Заказы</a>
				</li>
				<li>
					<a href="/admin/shop/clients/">Клиенты</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/auth/group/"><i class="icon-lock"></i>Пользователи и группы
			</a>
			<ul>
				<li>
					<a href="/admin/auth/group/">Группы</a>
				</li>
			</ul>
		</li>
        <li class="active">
			<a href="/admin/settings/"><i class="icon-home"></i>Настройки</a>
		</li>
        <li>
			<a href="/admin/email/"><i class="icon-home"></i>Рассылка</a>
		</li>
	</ul>
</div>
{% endblock %}

{% block content %}
    <ul class="breadcrumb" style="display: block">
        <li>
            <a href="/admin/">Начало</a>
            <span class="divider">»</span>
        </li>
        <li class="active">
            Настройки
        </li>
    </ul>

    <div id="content" class="colM row-fluid">
       <h2 class="content-title">Email рассылка</h2>
       <div id="content-main" class="inner-two-columns">
       <form enctype="multipart/form-data" action="" method="post" id="product_form" class="form-horizontal">
             <div class="inner-right-column">
                <div class="box save-box">
                   <div class="submit-row clearfix">
                      <button type="submit" class="btn btn-high btn-info" name="_save">Отправить</button>
                   </div>
                </div>
             </div>
             <div class="inner-center-column">
                {% csrf_token %}
                <div class="tab-content tab-content-main">

                    <fieldset class="module aligned first ">
                        <div class="control-group form-row field-site_name ">
                            <div>
                                <div class="control-label"><label class="required" for="id_site_name">Название сайта:</label></div>
                                <div class="controls">{{ form.site_name }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-description ">
                            <div>
                                <div class="control-label"><label class="required" for="id_description">Description:</label></div>
                                <div class="controls">{{ form.description }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-keywords ">
                            <div>
                                <div class="control-label"><label class="required" for="id_keywords">Keywords:</label></div>
                                <div class="controls">{{ form.keywords }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-phone ">
                            <div>
                                <div class="control-label"><label class="required" for="id_phone">Телефон:</label></div>
                                <div class="controls">{{ form.phone }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-email ">
                            <div>
                                <div class="control-label"><label class="required" for="id_email">E-mail:</label></div>
                                <div class="controls">{{ form.email }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-vk ">
                            <div>
                                <div class="control-label"><label class="required" for="id_vk">Вк:</label></div>
                                <div class="controls">{{ form.vk }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-inst ">
                            <div>
                                <div class="control-label"><label class="required" for="id_inst">Instagram:</label></div>
                                <div class="controls">{{ form.inst }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-head_banner ">
                            <div>
                                <div class="control-label"><label for="id_head_banner">Баннер (главный):</label></div>

                                <div class="controls">
                                    <div class="file-upload">{{ form.head_banner }}</div>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                </div>
             </div>
          </form>
       </div>
    </div>
{% endblock %}

mysite/accounts/templates/ajax_login.html
<h4>Вход в личный кабинет DaryaShop</h4>

<form class="popupBoxLoginForm" action="" style="position: relative">
    {% csrf_token %}
    <label for="">Ваш номер телефона</label>
    {{ form.login }}
    <label for="">Ваш пароль</label>
    {{ form.password }}
    {{ form.is_remember }}
    <label class="popupBoxLoginFormZap" for="">Запомнить меня</label>
    <a href="#" class="popupBoxLoginFormVos">Забыли пароль?</a>
    {% if error %}
    <p style="color: #ff0000; position: absolute; top: 120px; left: -30px;">{{ error }}</p>
    {% endif %}
    <a class="popupBoxBottom loginSubmit" href="#">Войти</a>
</form>

<img class="popupBoxLoginFormClose" src="/static/images/cross97.png">

mysite/accounts/templates/my_order.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Заказ #{{ order.id }}</h1>
    </div>
    <div class="ContentBoxPage">
        <h5 style="font-weight: bold">Доставка - {{ order.type_delivery.title }}</h5>
        <p>{{ order.user.name }} {{ order.user.surname }}</p>
        <p>{{ order.index }}, {{ order.region }}, {{ order.city }}, {{ order.address }}</p>

        <table>
            {% for product in order.products %}
            <tr>
                <td>
                    <div style="width: 40px; height: 35px; float: left; margin-right: 10px; overflow: hidden;">
                        <img style="width: 40px;" src="/static/uploads/{{ product.image }}" alt="{{ product.name }}"/>
                    </div>
                    <p>{{ product.name }}</p>
                </td>
                <td align="center">{{ product.price }} руб. x {{ product.count }}</td>
                <td align="center">{{ product.price_all }} руб.</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2" align="right">Доставка ({{ order.type_delivery.title }})</td>
                <td align="center">{{ order.type_delivery.price }} руб.</td>
            </tr>
            <tr>
                <td style="font-weight: bold" colspan="2" align="right">Итого</td>
                <td style="font-weight: bold" align="center">{{ order.sum }} руб.</td>
            </tr>
        </table>
	</div>
</div>
{% endblock %}

mysite/accounts/templates/my_orders.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Личный кабинет</h1>
    </div>
    <div class="ContentBoxPage">
        {% if orders %}
        <table>
            <tr>
                <td>Номер</td>
                <td>Статус заказа</td>
                <td width="300px">Товары</td>
                <td>Доставка</td>
                <td width="100px">Дата заказа</td>
            </tr>
            {% for order in orders %}
            <tr>
                <td align="center"><a href="/user/order/{{ order.id }}/">#{{ order.id }}</a></td>
                <td><p style="background: #ed145b;padding: 2px 4px;color: #fff;">{{ order.status }}</p></td>
                <td width="300px">
                    <ul>
                        {% for product in order.products %}
                        <li><p>{{ product.name }}</p> x {{ product.count }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{ order.type_delivery.title }}</td>
                <td width="100px">{{ order.date_create }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>Вы ещё ничего не заказывали</p>
        {% endif %}
	</div>
</div>
{% endblock %}

mysite/accounts/templates/my_orders_not_registered.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Личный кабинет</h1>
    </div>
    <div class="ContentBoxPage">
        <p>Вы не вошли в систему - <a href="#" class="login_order">войти</a> или <a href="/registration/">зарегистрироваться</a></p>
	</div>
    <div style="clear: both"></div>
</div>
{% endblock %}

mysite/accounts/templates/registration.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Регистрация</h1>
    </div>
    <div class="OrderBox">
        <form action="/registration/" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="OrderBoxUserData RegistrationBox">

                <div class="OrderBoxAddressTypeItem" style="width: 303px;">
                    <label>Имя <span style="color: #ff0000">{{ form.first_name.errors }}</span></label>
                    {{ form.first_name }}
                </div>

                <div class="OrderBoxAddressTypeItem" style="width: 303px;">
                    <label>Электронная почта <span style="color: #ff0000">{{ form.email.errors }}</span></label>
                    {{ form.email }}
                </div>

                <div class="OrderBoxAddressTypeItem" style="width: 303px;">
                    <label>Фамилия <span style="color: #ff0000">{{ form.last_name.errors }}</span></label>
                    {{ form.last_name }}
                </div>

                <div class="OrderBoxAddressTypeItem" style="width: 303px;">
                    <label>Телефон <span style="color: #ff0000">{{ form.phone.errors }}</span></label>
                    {{ form.phone }}
                </div>
                <div class="OrderBoxAddressTypeItem" style="width: 303px; float: right">
                    <input type="submit" class="OrderSubmit" style="margin: 25px 40px 0 17px;" value="Зарегистрироваться"/>
                </div>

                <div style="clear: both"></div>
            </div>

            <div style="clear: both"></div>
        </form>
	</div>
</div>
{% endblock %}

mysite/accounts/templates/registration_thank.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Регистрация</h1>
    </div>
    <div class="ContentBoxPage">
        <p>Спасибо, вы зарегистрированы</p>
        <p>Вы можете войти в <a class="login_order" href="/user/orders/">личный кабинет</a> для просмотра своих заказов</p>
        <p>Данные для входа:</p>
        <p>Телефон: {{ username }}</p>
        <p>Пароль: {{ password }}</p>
	</div>
</div>
{% endblock %}

mysite/accounts/templates/registrations.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Регистрация</h1>
    </div>
    <div class="OrderBox">
        <form action="/registrations/" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="OrderBoxUserData">
                <h4>Контактная информация</h4>

                <label>Имя <span style="color: #ff0000">{{ form.first_name.errors }}</span></label>
                {{ form.first_name }}

                <label>Фамилия <span style="color: #ff0000">{{ form.last_name.errors }}</span></label>
                {{ form.last_name }}

                <label>Электронная почта <span style="color: #ff0000">{{ form.email.errors }}</span></label>
                {{ form.email }}

                <label>Телефон <span style="color: #ff0000">{{ form.phone.errors }}</span></label>
                {{ form.phone }}
            </div>

            <input type="submit" value="Зарегистрироваться"/>

            <div style="clear: both"></div>
        </form>
	</div>
</div>
{% endblock %}

mysite/accounts/templates/yes.html
true