mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'catalog.views.home'),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^admin/catalog/product/add/$', 'catalog.views.product_form', name="start"),
    url(r'^admin/catalog/product/(?P<id>\d+)/$', 'catalog.views.product_edit', name="start"),
    url(r'^admin/catalog/product/edit_ajax_related/$', 'catalog.views.product_edit_afax_related'),
    url(r'^admin/catalog/product/edit_ajax_research/(?P<pr_id>\d+)$', 'catalog.views.product_edit_ajax_research'),
    url(r'^admin/email/', 'shop.views.admin_email'),
    url(r'^admin/settings/', 'accounts.views.admin_settings'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'ajax-upload$', 'catalog.views.import_uploader', name="my_ajax_upload"),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^cart/', include('shop.urls')),
    url(r'^login/', 'accounts.views.ajax_login'),
    url(r'^logout/', 'accounts.views.logout'),
    url(r'^registration/$', 'accounts.views.registration'),
    url(r'^user/orders/', 'accounts.views.my_orders'),
    url(r'^user/order/(?P<id>\d+)/$', 'accounts.views.my_order'),
    url(r'', include('pages.urls')),
)

mysite/shop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'shop.views.cart'),
    url(r'^order/$', 'shop.views.order'),
    url(r'^add_in_cart/(?P<id>\d+)/$', 'shop.views.add_in_cart'),
    url(r'^del_in_cart/(?P<id>\d+)/$', 'shop.views.del_in_cart'),
    url(r'^remove_in_cart/(?P<id>\d+)/$', 'shop.views.remove_in_cart'),
    url(r'^cart_top_ajax/$', 'shop.views.cart_top_ajax')
)

mysite/catalog/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=250, verbose_name="Название")
    parent = models.ForeignKey("self", verbose_name="Родительская категория", blank=True, null=True, default="-1")
    url = models.CharField("Url", max_length=200, blank=True)
    description = models.CharField("Description", max_length=200, blank=True)
    keywords = models.CharField("Ключевые слова", max_length=200, blank=True)
    step = models.IntegerField("Вложенность", blank=True)

    class Meta:
        verbose_name_plural = u"Категории"
        verbose_name = u"Категория"

    def __unicode__(self):
        return self.title

    def get_all_product(self):
        mass_product = []

        def rec_category(obj):
            product = Product.objects.filter(category=obj)
            for product in product:
                mass_product.append(product)
            categories = Category.objects.filter(parent=obj)
            for category in categories:
                rec_category(category)

        rec_category(self)
        return mass_product

    def get_path_categ(self):
        mass_pass = []

        def rec_path(obj):
            if obj is not None:
                mass_pass.append(obj)
                rec_path(obj.parent)

        rec_path(self)
        return mass_pass


class Product(models.Model):
    name = models.CharField("Название", max_length=200)
    price = models.IntegerField("Цена")
    category = models.ForeignKey(Category, verbose_name="Категория", blank=True, null=True)
    sale = models.IntegerField("Скидка, %")
    sale_status = models.IntegerField("Сделать скидку", default=0)
    count_status = models.IntegerField("Под заказ", default=0)
    count = models.IntegerField("Товар в наличии")
    status = models.IntegerField("Рекламные метки", default=0)
    text = models.TextField("Описание")
    color = models.CharField("Цвет", max_length=200, blank=True)
    size = models.CharField("Размер", max_length=200, blank=True)
    structure = models.CharField("Состав", max_length=200, blank=True)
    keywords = models.CharField("Ключевые слова", max_length=200)
    description = models.CharField("Description", max_length=200)
    images = models.TextField(blank=True)
    image = models.CharField(max_length=200, blank=True)
    related_products = models.CharField(max_length=200, blank=True)
    home_status = models.IntegerField("На главной", default=0)

    class Meta:
        verbose_name_plural = u"Товары"
        verbose_name = u"Товар"

    def __unicode__(self):
        return self.name

    def is_home(self):
        if self.home_status == 0:
            return False
        return True

mysite/shop/models.py
# -*- coding: utf-8 -*-
from django.db import models
from accounts.models import User, Address
from mysite.smsc_api import *


Order_Status = (
    ('0', 'Обрабатывется'),
    ('1', 'Ждёт оплаты'),
    ('2', 'Оплачен'),
    ('3', 'Отправлен'),
)

St = {
    '0': 'Обрабатывется',
    '1': 'Ждёт оплаты',
    '2': 'Оплачен',
    '3': 'Отправлен'
}


def sms(phone, text):
    smsc = SMSC()
    r = smsc.send_sms(phone, text, sender="sms")


class TypeDelivery(models.Model):
    title = models.CharField("Название", max_length=200)
    description = models.TextField("Описание")
    price = models.IntegerField("Цена", default=0)

    class Meta:
        verbose_name = 'Вариант доставки'
        verbose_name_plural = 'Варианты доставки'

    def __unicode__(self):
        return self.title


class UserCart(models.Model):
    user_key = models.CharField("Ключ", max_length=200)
    products = models.CharField("Товары", max_length=200)


class Order(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", blank=True, null=True)
    type_delivery = models.ForeignKey(TypeDelivery, verbose_name="Вариант доставки", null=True)
    products = models.CharField("Заказ", max_length=200)
    status = models.CharField("Статус", max_length=1, choices=Order_Status)
    date_create = models.DateField(verbose_name="Дата создания заказа", auto_now_add=True)
    date_change = models.DateField(verbose_name="Дата редактирования заказа", auto_now=True)
    admin_comment = models.TextField(verbose_name="Комментарий администратора", blank=True)
    sum = models.IntegerField("Сумма заказа", default=0)

    name = models.CharField("Имя", max_length=200)
    surname = models.CharField("Фамилия", max_length=200)
    phone = models.CharField("Телефон", max_length=200)
    mail = models.CharField("Имя", max_length=200)

    region = models.CharField("Область", max_length=200)
    city = models.CharField("Город", max_length=200)
    index = models.CharField("Индекс", max_length=200)
    address = models.CharField("Адрес", max_length=200)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __unicode__(self):
        return self.date_create.strftime('%d-%m-%y') + '(' + self.name + ' ' + self.surname + ')'

    def order_title(self):
        return '<a href="#">' + self.name + ' ' + self.surname + '</a>'

    order_title.allow_tags = True

    def order_date(self):
        return self.date_create.strftime('%d-%m-%y')

    def save(self, *args, **kwargs):
        model_old = Order.objects.get(id=self.id)
        if model_old.status != self.status:
            phone = self.phone.replace("(", "")
            phone = phone.replace(")", "")
            phone = phone.replace(" ", "")
            phone = phone.replace("-", "")
            sms(phone, "Darya-Shop: Статус вашего заказа изменён - " + St[self.status])
        super(Order, self).save(*args, **kwargs)


class Clients(models.Model):
    name = models.CharField("Имя", max_length=200)
    surname = models.CharField("Фамилия", max_length=200)
    date_create = models.DateField(verbose_name="Дата", auto_now_add=True)
    phone = models.CharField("Телефон", max_length=200)
    mail = models.CharField("Имя", max_length=200)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __unicode__(self):
        return self.name + ' ' + self.surname

mysite/shop/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Order
from redactor.widgets import RedactorEditor


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['type_delivery', 'name', 'surname', 'mail', 'phone', 'region', 'city', 'index', 'address']
        widgets = {
            'address': forms.Textarea(),
        }


class MailSenderForm(forms.Form):
    theme = forms.CharField(label='Тема письма', max_length=200)
    text = forms.CharField(widget=RedactorEditor())

mysite/shop/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect
from django.core.context_processors import csrf
from django.core.mail import send_mail, EmailMultiAlternatives
from django.http import Http404
from shop.models import UserCart, TypeDelivery, Order, Clients
from catalog.models import Product
from accounts.models import Address, User
from additions import create_order, get_model_order, create_user, serialize, unserialize, update_user, random_str, sms
from forms import OrderForm, MailSenderForm
import random
import string
import xlrd


def return_cart(request):
    sum = 0
    count_all = 0
    products = []
    if "user_cart" in request.session:
        user_key = request.session["user_cart"]
        try:
            user_cart = UserCart.objects.get(user_key=user_key)
            for product_id, count in unserialize(user_cart.products).items():
                try:
                    pr = Product.objects.get(id=product_id)
                    if pr.sale_status == 1:
                        pr.price_new = (pr.price / 100) * (100 - pr.sale)
                    else:
                        pr.price_new = pr.price
                    pr.price_sum_new = pr.price_new * int(count)
                    pr.price_sum_old = pr.price * int(count)
                    pr.count = int(count)
                    products.append(pr)
                    count_all += int(count)
                    sum += pr.price_new * int(count)
                except Product.DoesNotExist:
                    pass
        except UserCart.DoesNotExist:
            pass
    return {'count': count_all, 'sum': sum, 'products': products}


def cart(request):
    cart_mass = return_cart(request)
    return render_to_response("cart.html", {'products': cart_mass['products'], 'sum': cart_mass['sum']})


def order(request):
    args = {}
    args.update(csrf(request))
    cart_mass = return_cart(request)
    args['types_delivery'] = TypeDelivery.objects.all()
    args['sum'] = cart_mass['sum']
    args['form'] = OrderForm()

    if request.user.is_authenticated():
        if request.POST:
            form = OrderForm(request.POST)
            if form.is_valid():
                ord = create_order(request, request.user)
                user = update_user(request)
                # отправка на e-mail и sms
                phone = user.phone.replace("(", "")
                phone = phone.replace(")", "")
                phone = phone.replace(" ", "")
                phone = phone.replace("-", "")
                sms(phone, "Darya-Shop: Ваш заказ оформлен")
                return render_to_response("order_thanks.html")
            else:
                args['form'] = form
                return render_to_response("order_registered.html", args)
        model = get_model_order(request)
        args['form'] = OrderForm(instance=model)
        args['user'] = request.user
        return render_to_response("order_registered.html", args)

    if request.POST:
        form = OrderForm(request.POST)
        if form.is_valid():
            password = random_str(7)
            user = create_user(request, password)
            if user:
                ord = create_order(request, user)
                # отправка на e-mail и sms
                phone = user.phone.replace("(", "")
                phone = phone.replace(")", "")
                phone = phone.replace(" ", "")
                phone = phone.replace("-", "")
                message = "Darya-Shop. Ваш заказ оформлен! Данные для входа в личный кабинет: \nлогин: %s \nпароль: %s" % (
                    phone.encode('utf-8'), password.encode('utf-8'))
                sms(phone, message)
                return render_to_response("order_thanks.html", {'ord': ord, 'password': password})
            else:
                args['error'] = "Вы уже зарегистрированны - войдите в систему"
                args['form'] = form
        else:
            args['form'] = form
        return render_to_response("order_not_registered.html", args)

    return render_to_response("order_not_registered.html", args)


def add_in_cart(request, id=-1):
    if "user_cart" in request.session:
        user_key = request.session["user_cart"]
        try:
            user_cart = UserCart.objects.get(user_key=user_key)
        except UserCart.DoesNotExist:
            user_cart = UserCart()
            user_cart.user_key = user_key
        products = unserialize(user_cart.products)
        products[int(id)] = products.get(int(id), 0) + 1
        user_cart.products = serialize(products)
        user_cart.save()
    else:
        user_cart = UserCart()
        user_cart.user_key = "".join(
            random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for x in range(16))
        user_cart.products = str(id) + ":1"
        request.session["user_cart"] = user_cart.user_key
        user_cart.save()
    cart_mass = return_cart(request)
    if 'cart' in request.GET:
        return render_to_response("cart_ajax.html", {'products': cart_mass['products'], 'sum': cart_mass['sum']})
    return render_to_response("add_in_cart.html", {'count': cart_mass['count'], 'sum': cart_mass['sum']})


def del_in_cart(request, id=-1):
    if "user_cart" in request.session:
        user_key = request.session["user_cart"]
        try:
            user_cart = UserCart.objects.get(user_key=user_key)
        except UserCart.DoesNotExist:
            user_cart = UserCart()
            user_cart.user_key = user_key
        products = unserialize(user_cart.products)
        if int(id) in products and products[int(id)] > 0:
            products[int(id)] -= 1
            if products[int(id)] == 0:
                products.pop(int(id))
            user_cart.products = serialize(products)
            user_cart.save()
    cart_mass = return_cart(request)
    return render_to_response("cart_ajax.html", {'products': cart_mass['products'], 'sum': cart_mass['sum']})


def remove_in_cart(request, id=-1):
    if "user_cart" in request.session:
        user_key = request.session["user_cart"]
        try:
            user_cart = UserCart.objects.get(user_key=user_key)
        except UserCart.DoesNotExist:
            user_cart = UserCart()
            user_cart.user_key = user_key
        products = unserialize(user_cart.products)
        products.pop(int(id))
        user_cart.products = serialize(products)
        user_cart.save()
    cart_mass = return_cart(request)
    return render_to_response("cart_ajax.html", {'products': cart_mass['products'], 'sum': cart_mass['sum']})


def cart_top_ajax(request):
    cart_mass = return_cart(request)
    return render_to_response("cart_top_ajax.html", {'count': cart_mass['count'], 'sum': cart_mass['sum']})


def admin_email(request):
    if request.user.is_authenticated():
        args = {}
        args.update(csrf(request))
        args['form'] = MailSenderForm()
        if request.POST:
            form = MailSenderForm(request.POST)
            if form.is_valid():
                clients = Clients.objects.all()
                clients_mails = []
                for client in clients:
                    clients_mails.append(client.mail)
                subject, from_email, to = request.POST.get('theme'), 'from@example.com', ['marshinskii@gmail.com']
                text_content = request.POST.get('text')
                html_content = request.POST.get('text')
                msg = EmailMultiAlternatives(subject, text_content, from_email, clients_mails)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                pass
            else:
                args['form'] = MailSenderForm(request.POST)
        return render_to_response("admin_email.html", args)
    else:
        return redirect('/admin/')

mysite/shop/templates/add_in_cart.html
<h4>Товар добавлен в корзину</h4>

<p style="margin-top: 47px;">Всего товаров в корзине: <span>{{ count }} шт.</span></p>
<p>На сумму: <span>{{ sum }} руб.</span></p>
<a class="popupBoxOrder" href="/cart/order/">Оформить заказ</a>
<a class="popupBoxOpenCart" href="/cart/"><img src="/static/images/shopping122.png" alt=""/><span>Открыть корзину</span></a>

<img class="popupBoxLoginFormClose" src="/static/images/cross97.png">

mysite/shop/templates/admin_email.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block extrahead %}{{ block.super }}
    <meta charset="UTF-8">
    <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
    <script src="{% static "ajaxuploader/js/fileuploader.js" %}" ></script>
    <link href="{% static "ajaxuploader/css/fileuploader.css" %}" media="screen" rel="stylesheet" type="text/css" />
    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />

    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/redactor/jquery.redactor.init.js"></script>
    <script type="text/javascript" src="/static/redactor/redactor.js"></script>
    <script type="text/javascript" src="/static/redactor/langs/ru.js"></script>
    <script>
        function randWD(n){  // [ 2 ] random words and digits
            return Math.random().toString(36).slice(2, 2 + Math.max(1, Math.min(n, 10)) );
        }
        function set_cookie(name, value, expires)
        {
            if (!expires)
            {
                expires = new Date();
            }
            document.cookie = name + "=" + escape(value) + "; expires=" + expires.toGMTString() +  "; path=/";
        }
        function get_cookie(name)
        {
            var cookie_name = name + "=";
            var cookie_length = document.cookie.length;
            var cookie_begin = 0;
            while (cookie_begin < cookie_length)
            {
                var value_begin = cookie_begin + cookie_name.length;
                if (document.cookie.substring(cookie_begin, value_begin) == cookie_name)
                {
                    var value_end = document.cookie.indexOf (";", value_begin);
                    if (value_end == -1)
                    {
                        value_end = cookie_length;
                    }
                    return unescape(document.cookie.substring(value_begin, value_end));
                }
                cookie_begin = document.cookie.indexOf(" ", cookie_begin) + 1;
                if (cookie_begin == 0)
                {
                break;
                }
            }
            return null;
        }

        var click_head_img = function(){
            var parent = $(this).parent("div");
            var img = parent.attr("data-image");
            $("#hidden_image").val(img);
            $(".hidden_image_active").css('opacity', '0.3');
            $(".hidden_image_active").removeClass("hidden_image_active");
            $(this).addClass("hidden_image_active");
            $(this).css('opacity', '1');
        }

        var expires = new Date(); // получаем текущую дату
        expires.setTime(expires.getTime() + (1000 * 86400 * 365));
        set_cookie("filename", randWD(8), expires);

        $(function(){
            var uploader = new qq.FileUploader({
                action: "/ajax-upload",
                element: $('#file-uploader')[0],
                multiple: true,
                onComplete: function(id, fileName, responseJSON) {
                    if(responseJSON.success) {
                        var wer = get_cookie("filename") + '.' + fileName.split('.')[1];
                        $(".adminBoxImgLast").before('<div class="adminBoxImg"><img src="/static/uploads/' + wer + '" alt=""/><div data-image="' + wer + '" class="adminBoxSettingsImages"><img class="adminBoxImgClose" src="/static/images/close_icon.png" alt="Удалить"/><img class="adminBoxImgHead" src="/static/images/icon_writing.png" alt="Главная"/></div></div>');
                        var expires = new Date(); // получаем текущую дату
                        expires.setTime(expires.getTime() + (1000 * 86400 * 365));
                        set_cookie("filename", randWD(8), expires);
                        var img = $('#hidden_images').val();
                        var str = img + ';' + wer;
                        $('#hidden_images').val(str);

                        if($(".adminBoxImg").size() == 2)
                        {
                            var img2 = $(".adminBoxImg").eq(0).children(".adminBoxSettingsImages").attr("data-image");
                            $("#hidden_image").val(img2);

                            var icon = $(".adminBoxImg").children(".adminBoxSettingsImages").children(".adminBoxImgHead");
                            icon.addClass("hidden_image_active");
                            icon.css('opacity', '1');
                        }
                    } else {
                        alert("upload failed!");
                    }
                },
                params: {
                    'csrf_token': '{{ csrf_token }}',
                    'csrf_name': 'csrfmiddlewaretoken',
                    'csrf_xname': 'X-CSRFToken'
                }
            });
        });

        $(document).ready(function(){
            $(".adminCatalogSearchProduct").hide();
            $("#id_search_products_ajax").keyup(function(){
                var key = $("#id_search_products_ajax").val();
                $(".adminCatalogSearchProduct").load("/admin/catalog/product/edit_ajax_related/?key=" + key);
                $(".adminCatalogSearchProduct").show(400);

                $(".controls").click(function(){
                    $(".adminCatalogSearchProduct").hide(300);
                });
            });

            $(".adminCatalogSearchProductItem").live("click", function(){
                var val = $("#id_related_products").val();
                val = val + ";" + $(this).attr("data-id");
                $("#id_related_products").val(val);

                $(".adminCatalogResearchProducts").append('<div class="adminCatalogResearchProductsItem"></div>');
                $(".adminCatalogResearchProductsItem").last().hide();
                $(".adminCatalogResearchProductsItem").last().load("/admin/catalog/product/edit_ajax_research/" + $(this).attr("data-id"));
                $(".adminCatalogResearchProductsItem").last().show(300);
            });

            $(".adminBoxImgClose").live("click", function(){
                var parent = $(this).parent("div");
                var img = parent.attr("data-image");
                var images = $("#hidden_images").val();
                $("#hidden_images").val(images.replace(';' + img, ''));
                parent.parent("div").remove();

                var parent = $(".adminBoxImgClose").parent("div");
                if(parent.children(".adminBoxImgHead"))
                {
                    var img2 = $(".adminBoxImg").eq(0).children(".adminBoxSettingsImages").attr("data-image");
                    $("#hidden_image").val(img2);

                    var icon = $(".adminBoxImg").eq(0).children(".adminBoxSettingsImages").children(".adminBoxImgHead");
                    icon.addClass("hidden_image_active");
                    icon.css('opacity', '1');
                }
            });

            $(".adminBoxImgHead").live('click', click_head_img);

            $(".adminBoxProductsClose").live("click", function(){
                var current = $(this).parent("div").attr("data-id");
                var val = $("#id_related_products").val();
                $("#id_related_products").val(val.replace(';' + current, ''));
                $(this).parents(".adminCatalogResearchProductsItem").hide(300);
                $(this).remove();
            });
        });
    </script>
    <style>
    .breadcrumb {
        display: none;
    }
    #product_form input[type="text"] {
        width: 450px;
    }
    </style>
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block my_left_menu %}
<div class="left-nav" id="left-nav">
	<ul>
		<li>
			<a href="/admin/"><i class="icon-home"></i>Начало
			</a>
		</li>
		<li>
			<a href="/admin/accounts/user/"><i class="icon-chevron-right"></i>Accounts
			</a>
			<ul>
				<li>
					<a href="/admin/accounts/user/">Пользователи</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/banners/rightbanner/"><i class="icon-chevron-right"></i>Banners
			</a>
			<ul>
				<li>
					<a href="/admin/banners/rightbanner/">Баннеры справа</a>
				</li>
				<li>
					<a href="/admin/banners/slider/">Слайдер</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/catalog/category/"><i class="icon-chevron-right"></i>Catalog
			</a>
			<ul>
				<li>
					<a href="/admin/catalog/category/">Категории</a>
				</li>
				<li>
					<a href="/admin/catalog/product/">Товары</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/pages/page/"><i class="icon-chevron-right"></i>Pages
			</a>
			<ul>
				<li>
					<a href="/admin/pages/page/">Страницы</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/shop/typedelivery/"><i class="icon-chevron-right"></i>Shop
			</a>
			<ul>
				<li>
					<a href="/admin/shop/typedelivery/">Варианты доставки</a>
				</li>
				<li>
					<a href="/admin/shop/order/">Заказы</a>
				</li>
				<li>
					<a href="/admin/shop/clients/">Клиенты</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/auth/group/"><i class="icon-lock"></i>Пользователи и группы
			</a>
			<ul>
				<li>
					<a href="/admin/auth/group/">Группы</a>
				</li>
			</ul>
		</li>
        <li>
			<a href="/admin/settings/"><i class="icon-home"></i>Настройки</a>
		</li>
        <li class="active">
			<a href="/admin/email/"><i class="icon-home"></i>Рассылка</a>
		</li>
	</ul>
</div>
{% endblock %}

{% block content %}
    <ul class="breadcrumb" style="display: block">
        <li>
            <a href="/admin/">Начало</a>
            <span class="divider">»</span>
        </li>
        <li class="active">
            Рассылка
        </li>
    </ul>

    <div id="content" class="colM row-fluid">
       <h2 class="content-title">Email рассылка</h2>
       <div id="content-main" class="inner-two-columns">
       <form enctype="multipart/form-data" action="" method="post" id="product_form" class="form-horizontal">
             <div class="inner-right-column">
                <div class="box save-box">
                   <div class="submit-row clearfix">
                      <button type="submit" class="btn btn-high btn-info" name="_save">Отправить</button>
                   </div>
                </div>
             </div>
             <div class="inner-center-column">
                {% csrf_token %}
                <div class="tab-content tab-content-main">
                   <fieldset class="module aligned first ">
                      <div class="control-group form-row field-name ">
                         <div>
                            <div class="control-label">
                                <label class="required" for="id_name">Тема рассылки:</label>
                            </div>
                             <div class="controls">
                                 {{ form.theme }}
                                 <span class="help-inline">
                                    {{ form.theme.errors }}
                                </span>
                             </div>
                         </div>
                      </div>

                       <div class="control-group form-row field-price ">
                         <div>
                            <div class="control-label">
                                <label class="required" for="id_price">Текст:</label>
                            </div>
                            <div class="controls">
                                {{ form.text }}
                                <span class="help-inline">
                                    {{ form.text.errors }}
                                </span>
                            </div>
                         </div>
                      </div>
                   </fieldset>

                </div>
             </div>
          </form>
       </div>
    </div>
{% endblock %}

mysite/shop/templates/cart_top_ajax.html
{% if count > 0 %}
<p>Корзина: <a href="/cart/">{{ count }} шт. - {{ sum }} руб.</a></p>
{% else %}
<p>Корзина: <a href="/cart/">пусто</a></p>
{% endif %}

mysite/shop/templates/order_thanks.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Заказ оформлен</h1>
    </div>
    <div class="ContentBoxPage">
        <p>Спасибо, ваш заказ оформлен</p>
        <p>Вы можете войти в <a href="/user/orders/">личный кабинет</a> для просмотра своих заказов</p>
        {% if password %}
        <p>Пароль: {{ password }}</p>
        <p>Тел.(логин): {{ ord.user.phone }}</p>
        {% endif %}
	</div>
</div>
{% endblock %}

mysite/shop/templates/top_cart.html
{% if count > 0 %}
<p>Корзина: <a href="/cart/">{{ count }} шт. - {{ sum }} руб.</a></p>
{% else %}
<p>Корзина: <a href="/cart/">пусто</a></p>
{% endif %}